apiVersion: apps/v1
kind: Deployment
metadata:
  name: milestone-deployment
  labels:
    app: milestone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: milestone
  template:
    metadata:
      labels:
        app: milestone
    spec:
      containers:
        - name: milestone
          image: liveorlike/milestone-tomcat:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: milestone
spec:
  selector:
    app: milestone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

status:
  loadBalancer: {}



